BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "article" (
	"id"	INTEGER NOT NULL UNIQUE,
	"created_by"	INTEGER,
	"updated_by"	INTEGER,
	"create_time"	INTEGER NOT NULL,
	"update_time"	INTEGER NOT NULL,
	"version"	INTEGER NOT NULL,
	"deleted"	INTEGER NOT NULL DEFAULT 'false',
	"title"	TEXT NOT NULL,
	"body"	TEXT NOT NULL,
	"published"	INTEGER NOT NULL DEFAULT 'false',
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
